name: polls
channels:
  - conda-forge
dependencies:
  - python
  - dash
  - dash-bootstrap-components
  - dash_html_components
  - plotly
  - pandas
  - numpy
  - taxcalc
  - pip
  - pip:
    - "git+git://github.com/PSLmodels/microdf.git"
    - "git+https://github.com/UBICenter/ubicenter.py"
