name: polls
channels:
  - conda-forge
dependencies:
  - python
  - dash
  - dash-bootstrap-components
  - plotly
  - pandas
  - numpy
  - pip
  - pip:
    - black
    # - kaleido
    # - numerize
    - "git+https://github.com/UBICenter/ubicenter"
